== 자녀 관련 API

=== 자녀 등록

operation::append-baby[snippets='http-request,request-parts,request-part-request-fields,http-response,response-fields']

=== 자녀 조회

operation::find-baby[snippets='http-request,path-parameters,http-response,response-fields']

=== 자녀 목록 조회

operation::find-babies[snippets='http-request,query-parameters,http-response,response-fields']

=== 자녀 프로필 사진 변경

operation::modify-baby-profile-image[snippets='http-request,path-parameters,request-parts,http-response,response-fields']

=== 자녀 닉네임 변경

operation::modify-baby-nickname[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 자녀 생년월일 변경

operation::modify-baby-birth[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 자녀 성별 변경

operation::modify-baby-gender[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== 자녀 삭제

operation::delete-baby[snippets='http-request,path-parameters,http-response,response-fields']